<a href="https://colab.research.google.com/github/Rahulpastam/Data-Mining/blob/main/CollegeDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1st week 31/07/24

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = np.genfromtxt('demodata_D.csv', delimiter=',')

In [ ]:
print(type(data))
data

<class 'numpy.ndarray'>


array([[14.    ,  3.    ,  0.    , ...,  4.    ,  1.5714,  0.    ],
       [ 5.    ,  3.    ,  0.    , ...,  1.    ,  0.8   ,  0.    ],
       [13.    ,  1.    ,  1.    , ...,  1.    ,  0.7692,  0.    ],
       ...,
       [23.    ,  1.    ,  0.    , ..., 24.    ,  2.3043,  0.    ],
       [11.    ,  1.    ,  8.    , ..., 22.    ,  4.6364,  1.    ],
       [ 4.    ,  2.    ,  0.    , ...,  5.    ,  1.75  ,  0.    ]])

In [ ]:
data1 = pd.read_csv('demodata1.csv')
data1

feature1  feature2  feature3  feature4  feature5  feature6  feature7  \
0          14         3         0         8        41        33         1   
1           5         3         0         9        43         0         0   
2          13         1         1         8        20        46         6   
3           8         4         0         7        35         4         0   
4          31         1         0         6        65       243         4   
..        ...       ...       ...       ...       ...       ...       ...   
351         5         3         0         7        19         4         4   
352        17         1         3        15        66        90         4   
353        23         1         0        31        82       201        22   
354        11         1         8        22        86        15         8   
355         4         2         0         3        16         0         0   

     feature8  feature9  feature10  ...  feature12  feature13  feature14  \
0           8        10    0.76068  ...    1.00000          2    0.74000   
1           9         5    0.66667  ...    1.00000          0    0.90244   
2           2         8    0.66667  ...    1.00000          0    0.00000   
3           7         7    0.71429  ...    1.00000          0    0.91765   
4           2        30    0.72667  ...    1.00000          0    0.00000   
..        ...       ...        ...  ...        ...        ...        ...   
351         4         4    0.75000  ...    0.00000          0    0.90244   
352        12         6    0.79167  ...    1.00000          2    0.00000   
353        27        17    0.89394  ...    0.44444          0    0.00000   
354        14         4    0.72857  ...    1.00000          7    0.00000   
355         3         4    0.33333  ...    1.00000          0    0.84211   

     feature15  feature16  feature17  feature18  feature19  feature20  \
0      0.35714          1          1    25.8570          4     1.5714   
1      0.53333          2          3    53.6000          1     0.8000   
2      0.61538          0          0     7.2308          1     0.7692   
3      0.46875          3          3    31.3750          5     1.3750   
4      0.18280          1          1    22.6130          4     1.1613   
..         ...        ...        ...        ...        ...        ...   
351    0.40000          1          1    28.8000          1     0.8000   
352    0.19792          0          0    35.8820         14     2.4118   
353    0.31818          0          0    45.7390         24     2.3043   
354    0.26667          0          0    77.7270         22     4.6364   
355    0.87500          1          1    13.5000          5     1.7500   

     feature21  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
351          0  
352          0  
353          0  
354          1  
355          0  

[356 rows x 21 columns]

In [ ]:
print(np.shape(data))

(356, 21)


In [ ]:
data.shape

(356, 21)

In [ ]:
np.shape(data[0])

(21,)

In [ ]:
np.shape(data[1])

(21,)

In [ ]:
np.savetxt('demodata2.csv', data, delimiter=',', fmt='%f')

In [ ]:
print(data1.shape)

(356, 21)


In [ ]:
data1.shape[0]

356

In [ ]:
data1.shape[1]

21

In [ ]:
data1.columns

Index(['feature1', 'feature2', 'feature3', 'feature4', 'feature5', 'feature6',
       'feature7', 'feature8', 'feature9', 'feature10', 'feature11',
       'feature12', 'feature13', 'feature14', 'feature15', 'feature16',
       'feature17', 'feature18', 'feature19', 'feature20', 'feature21'],
      dtype='object')

In [ ]:
data1.to_csv('demodata3.csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
floc = '/content/drive/MyDrive/DataMining/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
fname = floc + '1.csv'
data11 = np.genfromtxt(fname, delimiter=',')

In [ ]:
data11

array([[11.    ,  4.    ,  2.    , ...,  3.    ,  1.2727,  0.    ],
       [14.    ,  1.    ,  1.    , ...,  6.    ,  1.6429,  1.    ],
       [ 3.    ,  2.    ,  0.    , ...,  1.    ,  0.6667,  0.    ],
       ...,
       [14.    ,  1.    ,  0.    , ..., 24.    ,  2.7857,  1.    ],
       [ 4.    ,  2.    ,  0.    , ...,  5.    ,  1.75  ,  0.    ],
       [27.    ,  1.    ,  0.    , ..., 11.    ,  1.4444,  0.    ]])

In [ ]:
for i in range (1,33):
  fname = floc+ str(i)+ '.csv'
  data = np.genfromtxt(fname, delimiter=',')
  print('college:', i, '-> no.of students:', np.shape(data)[0], '-> no.of waiting students: ',
        np.sum(data[:, -1]))

college: 1 -> no.of students: 125 -> no.of waiting students:  20.0
college: 2 -> no.of students: 178 -> no.of waiting students:  40.0
college: 3 -> no.of students: 293 -> no.of waiting students:  32.0
college: 4 -> no.of students: 351 -> no.of waiting students:  92.0
college: 5 -> no.of students: 745 -> no.of waiting students:  166.0
college: 6 -> no.of students: 234 -> no.of waiting students:  27.0
college: 7 -> no.of students: 608 -> no.of waiting students:  216.0
college: 8 -> no.of students: 872 -> no.of waiting students:  145.0
college: 9 -> no.of students: 965 -> no.of waiting students:  188.0
college: 10 -> no.of students: 111 -> no.of waiting students:  63.0
college: 11 -> no.of students: 352 -> no.of waiting students:  40.0
college: 12 -> no.of students: 272 -> no.of waiting students:  90.0
college: 13 -> no.of students: 306 -> no.of waiting students:  75.0
college: 14 -> no.of students: 312 -> no.of waiting students:  79.0
college: 15 -> no.of students: 367 -> no.of waiting s

In [ ]:
a = [2,3,4,5,6,7,1,3]
a = np.array(a)
in1 = np.where(a >= 3)
print(in1[0], len(in1[0]))

[1 2 3 4 5 7] 6


In [ ]:
import math
def col_mx_mn(data):
  nof = np.shape(data)[1] - 1;
  val = np.zeros((nof, 4));
  in1 = np.where(data[:, -1] == 0);
  in2 = np.where(data[:, -1] == 1);

  for i in range(0, nof):
    fv = data[:, i]
    fv0 = fv[in1[0]]
    fv1 = fv[in2[0]]
    val[i,0] = np.mean(fv0) - np.std(fv0)*1.96/math.sqrt(len(in1[0]))
    val[i,1] = np.mean(fv0) + np.std(fv0)*1.96/math.sqrt(len(in1[0]))
    val[i,2] = np.mean(fv1) - np.std(fv1)*1.96/math.sqrt(len(in2[0]))
    val[i,3] = np.mean(fv1) + np.std(fv1)*1.96/math.sqrt(len(in2[0]))
  return val;

In [ ]:
import numpy as np
# generating min-max (CI) values min_max 1-32
for i in range(1,33):
  fname = floc+str(i)+'.csv';
  data = np.genfromtxt(fname, delimiter = ',')
  val = col_mx_mn(data)
  fname = floc+'Min_Max_'+str(i)+'.csv'
  np.savetxt(fname, val, delimiter = ',', fmt = '%f')


In [ ]:
# 2nd Week 07/08/24

In [ ]:
#calculating the ci values for individual feature
def civfeat(fv, jobd):
  in1 = np.where(jobd == 0)
  in2 = np.where(jobd == 1)

  fv0 = fv[in1[0]]
  fv1 = fv[in2[0]]

  val = np.zeros((2,2))
  val[0,0] = np.mean(fv0) - np.std(fv0)*1.96/math.sqrt(len(in1[0]))
  val[1,0] = np.mean(fv0) + np.std(fv0)*1.96/math.sqrt(len(in1[0]))
  val[0,1] = np.mean(fv1) - np.std(fv1)*1.96/math.sqrt(len(in2[0]))
  val[1,1] = np.mean(fv1) + np.std(fv1)*1.96/math.sqrt(len(in2[0]))
  return val;

In [ ]:
from matplotlib import pyplot
def figbox(data, p):
  pyplot.figure(figsize=(15,20))
  for i in range(0,20):
    fv = data[:,i]
    val = civfeat(fv, data[:,-1])
    pyplot.subplot(4,5,i+1)
    pyplot.boxplot(val, labels = ['JOB', 'NO JOB'])
    pyplot.grid(True)
    xlab = 'Feature_'+str(i+1)
    pyplot.xlabel(xlab)
    pyplot.ylabel('95%CI')
  fname = floc+'CI_Value_BoxPlot' + str(p) + '.jpg'
  pyplot.savefig(fname)
  pyplot.close()

In [ ]:
for i in range(1,33):
  fname = floc+str(i)+'.csv';
  data = np.genfromtxt(fname, delimiter=',')
  figbox(data, i)

In [ ]:
data

array([[ 8.    ,  4.    ,  0.    , ...,  1.    ,  0.5   ,  1.    ],
       [21.    ,  1.    ,  0.    , ..., 24.    ,  4.7619,  0.    ],
       [ 1.    ,  1.    ,  0.    , ...,  1.    ,  1.    ,  0.    ],
       ...,
       [ 3.    ,  1.    ,  0.    , ...,  1.    ,  1.    ,  1.    ],
       [ 5.    ,  1.    ,  0.    , ...,  9.    ,  2.2   ,  0.    ],
       [ 1.    ,  1.    ,  0.    , ...,  1.    ,  1.    ,  1.    ]])

In [ ]:
def zvalue(fv, jobd): #fv - feature vector
  in1 = np.where(jobd==0)
  in2 = np.where(jobd==1)
  fv0 = fv[in1[0]]
  fv1 = fv[in2[0]]
  m0 = np.mean(fv0)
  m1 = np.mean(fv1)

  if(m0==0 and m1==0):
    return 0

  var0 = np.std(fv0)
  var1 = np.std(fv1)

  zv = (m0-m1)/math.sqrt(var0*var0/len(in1[0])+var1*var1/len(in2[0]))
  return np.abs(zv)

In [ ]:
from statsmodels.stats.weightstats import ztest
#calculating zvalue of individual feature using ztest - predefined function
def zpython(fv, jobd):
  in1=np.where(jobd==0)
  in2=np.where(jobd==1)
  fv0=fv[in1[0]]
  fv1=fv[in2[0]]
  m0=np.mean(fv0)
  m1=np.mean(fv1)
  if m0==0 and m1==0:
    return 0,0
  zv,pv=ztest(fv0,fv1,alternative='two-sided')
  return np.abs(zv),pv

In [ ]:
#calculating z-cvalue for each feature using the zvalue function
from scipy import stats
def zall(data):
  zv=np.zeros((np.shape(data)[1]-1))
  pv=np.zeros((np.shape(data)[1]-1))
  for i in range(0,np.shape(data)[1]-1):
    fv=data[:,i]
    zv[i]=zvalue(fv,data[:,-1])
    pv[i]=stats.norm.sf(zv[i])*2
  return zv,pv

In [ ]:
#ranksum test
def rstf(fv, jobd):
  in1=np.where(jobd==0)
  in2=np.where(jobd==1)
  fv0=fv[in1[0]]
  fv1=fv[in2[0]]
  rs,pv=stats.ranksums(fv0,fv1)
  return pv

In [ ]:
#ranksum test for individual feature
from scipy import stats
def rst(data):
  pv=np.zeros((np.shape(data)[1]-1))
  for i in range(0,np.shape(data)[1]-1):
    fv=data[:,i]
    pv[i]=rstf(fv,data[:,-1])
  return pv

In [ ]:
#calculating z-value for each feature using the zpython function
def zall1(data):
  zv=np.zeros((np.shape(data)[1]-1))
  pv=np.zeros((np.shape(data)[1]-1))
  for i in range(0,np.shape(data)[1]-1):
    fv=data[:,i]
    zv[i],pv[i]=zpython(fv,data[:,-1])
  return zv,pv

In [ ]:
zv, pv = zall(data)
zv

array([3.19996385, 1.77194446, 1.50665333, 0.09994421, 2.89585758,
       2.05678127, 0.89175444, 1.60569342, 3.57512557, 1.80566683,
       1.57061362, 0.5539881 , 2.50962715, 2.52852206, 1.71771098,
       1.17870211, 0.91672156, 1.99257766, 0.17124223, 1.37431657])

In [ ]:
zv1, pv1 = zall1(data)

In [ ]:
in1 = np.where(pv1<=0.05)
in1

(array([ 0,  4,  5,  8, 12, 13]),)

In [ ]:
datan=data[:,in1[0]]
datan=np.append(datan,data[:,-1].reshape(np.shape(data)[0],1),axis=1)

In [ ]:
np.shape(datan)

(162, 7)

In [ ]:
#z-values 33-64
for i in range(1,33):
  fname = floc+str(i)+'.csv';
  data=np.genfromtxt(fname,delimiter=',')
  zv,pv=zall(data)
  in1=np.where(pv<=0.05)
  print('College=',i,len(in1[0]),in1[0])
  datan=data[:,in1[0]]
  datan=np.append(datan,data[:,-1].reshape(np.shape(data)[0],1),axis=1)
  fname=floc+str(i+32)+'.csv'
  np.savetxt(fname,datan,delimiter=',',fmt='%f')

College= 1 8 [ 0  4  7  9 10 11 14 18]
College= 2 3 [ 6  7 13]
College= 3 13 [ 0  1  4  6  7  8  9 10 11 12 14 15 16]
College= 4 14 [ 0  3  4  5  7  8  9 10 11 12 14 15 18 19]
College= 5 16 [ 0  3  4  5  7  8  9 10 11 12 14 15 16 17 18 19]
College= 6 11 [ 0  3  4  6  7  8 10 12 13 14 17]
College= 7 10 [ 0  2  3  4  8 10 12 14 18 19]
College= 8 16 [ 0  2  3  4  6  7  8 10 11 12 14 15 16 17 18 19]
College= 9 17 [ 0  2  3  4  6  7  8  9 10 11 12 14 15 16 17 18 19]
College= 10 11 [ 0  3  4  5  7  8 10 14 15 16 17]
College= 11 14 [ 0  3  4  5  7  8  9 10 11 12 14 17 18 19]
College= 12 16 [ 1  3  4  6  7  8  9 11 12 13 14 15 16 17 18 19]
College= 13 15 [ 0  3  4  6  7  8  9 10 11 12 14 16 17 18 19]
College= 14 17 [ 0  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 19]
College= 15 14 [ 0  3  4  6  7  8  9 10 11 12 14 16 18 19]
College= 16 13 [ 0  3  4  5  6  7  8 10 11 12 14 18 19]
College= 17 11 [ 0  3  4  5  7  8 10 12 14 18 19]
College= 18 7 [ 0  2  3  6  8 11 16]
College= 19 14 [ 0  2  3  4 

In [ ]:
#ranksum test 65-96
for i in range(1,33):
  fname = floc+str(i)+'.csv';
  data=np.genfromtxt(fname,delimiter=',')
  pv=rst(data)
  in1=np.where(pv<=0.05)
  print('College=',i,len(in1[0]),in1[0])
  datan=data[:,in1[0]]
  datan=np.append(datan,data[:,-1].reshape(np.shape(data)[0],1),axis=1)
  fname=floc+str(i+32*2)+'.csv'
  np.savetxt(fname,datan,delimiter=',',fmt='%f')

College= 1 12 [ 0  3  4  5  6  7  8 10 14 17 18 19]
College= 2 2 [3 7]
College= 3 13 [ 0  1  3  4  5  7  8 10 12 14 15 17 18]
College= 4 14 [ 0  3  4  5  7  8 10 11 12 13 14 17 18 19]
College= 5 16 [ 0  3  4  5  6  7  8 10 11 12 14 15 16 17 18 19]
College= 6 10 [ 0  3  4  5  7  8 10 12 14 17]
College= 7 9 [ 0  3  4  5  6  8 10 18 19]
College= 8 16 [ 0  1  3  4  5  6  7  8 10 12 14 15 16 17 18 19]
College= 9 16 [ 0  2  3  4  5  6  7  8  9 10 11 12 14 17 18 19]
College= 10 9 [ 0  3  4  5  7  8 10 14 17]
College= 11 13 [ 0  3  4  5  7  8 10 11 12 14 17 18 19]
College= 12 18 [ 0  1  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19]
College= 13 15 [ 0  3  4  5  6  7  8  9 10 11 12 14 17 18 19]
College= 14 14 [ 0  3  4  5  6  7  8 10 11 12 14 17 18 19]
College= 15 14 [ 0  3  4  5  6  7  8 10 11 12 14 17 18 19]
College= 16 13 [ 0  3  4  5  6  7  8 10 11 14 17 18 19]
College= 17 12 [ 0  3  4  5  7  8 10 11 12 14 18 19]
College= 18 4 [ 3  6  8 11]
College= 19 12 [ 0  3  4  7  8 10 11 12 14 16 17 

In [ ]:
  #testing the logic for rst function for a single dats set
  fname = floc+str(2)+'.csv';
  data=np.genfromtxt(fname,delimiter=',')
  pv=rst(data)
  in1=np.where(pv<=0.05)
  print('College=',2,len(in1[0]),in1[0])
  datan=data[:,in1[0]]
  datan=np.append(datan,data[:,-1].reshape(np.shape(data)[0],1),axis=1)
  # fname=floc+str(2)+'.csv'
  # np.savetxt(fname,datan,delimiter=',',fmt='%f')

College= 2 2 [3 7]


In [ ]:
zv[in1[0]]

array([0.09994421, 1.60569342])

In [ ]:
stats.norm.sf(1.1)*2 #survival function for two-tailed test.

0.27133212189276534

In [ ]:
# 3rd week 14/08/24

In [ ]:
data = np.genfromtxt('demodata_D.csv', delimiter=',')
r = np.corrcoef(data[:,0:-1], rowvar=False)
np.shape(r)

(20, 20)

In [ ]:
data.shape

(356, 21)

In [ ]:
r

array([[ 1.        ,  0.08447133,  0.07789268,  0.4615946 ,  0.87522178,
         0.85694032,  0.33583955,  0.5668794 ,  0.96091807, -0.17522183,
         0.7884214 ,  0.29815035,  0.58092092, -0.09533324, -0.56028666,
         0.30295138,  0.25015327,  0.03349798,  0.41852704,  0.17222709],
       [ 0.08447133,  1.        , -0.03640504,  0.01323809,  0.18207806,
         0.02407945, -0.09485515,  0.33905788,  0.08344236, -0.08232282,
         0.12590871,  0.17310419,  0.08647813,  0.83708085, -0.05183771,
         0.64348615,  0.57606516,  0.10395926, -0.04509135, -0.11518678],
       [ 0.07789268, -0.03640504,  1.        ,  0.41819766,  0.01523493,
         0.00917278,  0.41364239,  0.04937813,  0.06252703, -0.0582924 ,
        -0.01225249,  0.12042838,  0.1991668 , -0.05684344, -0.10996529,
        -0.00816957,  0.04579774, -0.06156769,  0.05579518,  0.04156765],
       [ 0.4615946 ,  0.01323809,  0.41819766,  1.        ,  0.36386611,
         0.44232393,  0.96468496,  0.24945522,  

In [ ]:
r = np.abs(r)
# cost correlation analysis
def ccra(r):
  impf = np.ones((np.shape(r)[1])) #asuming initially all the features are uncorrelated
  for i in range(0, np.shape(r)[1]-1):
    if(impf[i]==1):
      in1 = np.where(r[i:i+1:] >= 0.7)
      if(len(in1[0]) > 0):
        impf[i+1+in1[0]] = 0
  return impf

In [ ]:
in1 = ccra(r)
in1 = np.where(in1 == 1)
in1

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)

In [ ]:
np.corrcoef(data[:,in1[0]], rowvar=False)

array([[ 1.        ,  0.07789268,  0.87522178,  0.33583955,  0.96091807,
         0.7884214 ,  0.58092092, -0.56028666,  0.25015327,  0.41852704],
       [ 0.07789268,  1.        ,  0.01523493,  0.41364239,  0.06252703,
        -0.01225249,  0.1991668 , -0.10996529,  0.04579774,  0.05579518],
       [ 0.87522178,  0.01523493,  1.        ,  0.18647699,  0.77572508,
         0.90521911,  0.58209193, -0.57893288,  0.32232832,  0.52291577],
       [ 0.33583955,  0.41364239,  0.18647699,  1.        ,  0.3467963 ,
         0.16025737,  0.17996325, -0.15940558,  0.0162266 ,  0.07757385],
       [ 0.96091807,  0.06252703,  0.77572508,  0.3467963 ,  1.        ,
         0.67286614,  0.54896668, -0.47965432,  0.2180067 ,  0.34149636],
       [ 0.7884214 , -0.01225249,  0.90521911,  0.16025737,  0.67286614,
         1.        ,  0.50159194, -0.52861072,  0.28260155,  0.58753017],
       [ 0.58092092,  0.1991668 ,  0.58209193,  0.17996325,  0.54896668,
         0.50159194,  1.        , -0.38980871

In [ ]:
#ccra  97-128
for i in range(1,33):
  fname=floc+str(i)+'.csv';
  data=np.genfromtxt(fname,delimiter=',')
  r = np.corrcoef(data[:,0: -1], rowvar=False)
  r = np.abs(r)
  in1 = ccra(r)
  in1 = np.where(in1 == 1)
  datan=data[:,in1[0]]
  datan=np.append(datan,data[:,-1].reshape(np.shape(data)[0],1),axis=1)
  fname=floc+str(i+32*3)+'.csv'
  np.savetxt(fname,datan,delimiter=',',fmt='%f')

In [ ]:
datan.shape

(162, 11)

In [ ]:
#ccra on ranksum values 129-160
for i in range(1,33):
  fname = floc+str(i+32*2)+'.csv'
  data = np.genfromtxt(fname,delimiter=',')
  # print(str(i)+'.csv')

  r = np.corrcoef(data[:,0:-1],rowvar=False)
  r= abs(r)
  in1 = ccra(r)
  in1 = np.where(in1==1)[0]
  # print(len(in1))
  datan = data[:,in1]
  datan = np.concatenate((datan,data[:,-1].reshape(-1,1)),axis=1)
  fname = floc+str(i+32*4)+'.csv'
  np.savetxt(fname,datan,delimiter=',',fmt='%f')

In [ ]:
#  datan=np.append(datan,data[:,-1].reshape(np.shape(data)[0],1),axis=1)

In [ ]:
def gini(f, jobd):
  mf = np.median(f)
  in1 = np.where(f>=mf)
  in2 = np.where(f<mf)
  if len(in1[0])==0 or len(in2[0])==0:
    return 0.5

  job1 = jobd[in1[0]]
  job0 = jobd[in2[0]]

  n01 = np.sum(job0)
  n00 = len(job0)-n01

  n11 = np.sum(job1)
  n10 = len(job1)-n11

  p00 = n00 / (n00+n01)
  p01 = n01 / (n00+n01)
  p10 = n10 / (n00+n11)
  p11 = n11 / (n00+n11)

  gin0 = 1- (p00*p00) - (p01*p01)
  gin1 = 1- (p10*p10) - (p11*p11)

  fg = (len(job1)/len(f))*gin1 + (len(job0)/len(f))*gin0
  return fg

In [ ]:
# data = np.genfromtxt('demodata.csv', delimiter=',')

In [ ]:
# print(gini(data[:,0],data[:,-1]))

In [ ]:
#testing logic for 1.csv
data = np.genfromtxt(floc+'1.csv', delimiter=',')
datan = np.zeros((np.shape(data)[1]-1))
for j in range(np.shape(data)[1]-1):
  datan[j] =  gini(data[:,j],data[:,-1])
  # print(gini(data[:,j],data[:,-1]))
datan = np.argsort(datan)
datan = datan[:5]
in1 = data[:,datan]
in1 = np.concatenate((in1,data[:,-1].reshape(-1,1)),axis=1)
print(in1.shape)
# print(in1)

(125, 6)


In [ ]:
#gini important features  161-192
for i in range(1,33):
  data = np.genfromtxt(floc+str(i)+'.csv', delimiter=',')
  datan = np.zeros((np.shape(data)[1]-1))
  for j in range(np.shape(data)[1]-1):
    datan[j] =  gini(data[:,j],data[:,-1])
    # print(gini(data[:,j],data[:,-1]))
  datan = np.argsort(datan)
  datan = datan[:5]
  in1 = data[:,datan]
  in1 = np.concatenate((in1,data[:,-1].reshape(-1,1)),axis=1)
  fname = floc+str(i+32*5)+'.csv'
  np.savetxt(fname,in1,delimiter=',',fmt='%f')

In [ ]:
#4th Week 28/8/24

In [ ]:
import math

In [ ]:
def infogain(f, jobd):
  mf = np.median(f)
  in1 = np.where(f>=mf)
  in2 = np.where(f<mf)
  if len(in1[0])==0 or len(in2[0])==0:
    return 0.5

  job0 = jobd[in1[0]]
  job1 = jobd[in2[0]]

  n01 = np.sum(job0)
  n00 = len(in1[0])-n01

  n11 = np.sum(job1)
  n10 = len(in2[0])-n11

  p00 = n00 / (n00+n01)
  p01 = n01 / (n00+n01)
  p10 = n10 / (n11+n10)
  p11 = n11 / (n11+n10)

  n0 = np.sum(jobd)
  n1 = len(jobd) - n0
  p0 = n0 / len(jobd) if (n0+n1) != 0 else 0
  p1 = n1 / len(jobd) if (n0+n1)!= 0 else 0

  en0 = -p00*np.log2(p00) - p01*np.log2(p01)
  en1 = -p10*np.log2(p10) - p11*np.log2(p11)

  # fg = (len(job1)/len(f))*gin1 + (len(job0)/len(f))*gin0
  # return fg


  parent_en = -p0*np.log2(p0) - p1*np.log2(p1)
  childen0 = -p00*np.log2(p00)- p01*np.log2(p01)
  childen1 = -p11*np.log2(p11) - p10*np.log2(p10)

  info_gain = parent_en - (len(in1[0])/len(f))*childen0 - (len(in2[0])/len(f))*childen1
  # print(info_gain)
  return info_gain


In [ ]:
#info gain 193-224
for i in range(1,33):
  data = np.genfromtxt(floc+str(i)+'.csv', delimiter=',')
  datan = np.zeros((np.shape(data)[1]-1))
  for j in range(np.shape(data)[1]-1):
    datan[j] =  infogain(data[:,j], data[:,-1])
    # print(gini(data[:,j],data[:,-1]))
  datan = np.argsort(datan)
  datan = datan[-5:]
  in1 = data[:,datan]
  in1 = np.concatenate((in1,data[:,-1].reshape(-1,1)),axis=1)
  # print(in1)
  fname = floc+str(i+32*6)+'.csv'
  np.savetxt(fname,in1,delimiter=',',fmt='%f')

In [ ]:
for i in range(1, 33):
  data = np.genfromtxt(floc+str(i)+'.csv', delimiter=',')
  total = np.shape(data)[0]

  num_placed = np.sum(data[:, -1])
  placement_avg = (num_placed / total) * 100
  if 50 < placement_avg < 80:
        print('College:',i, ' No.of Students: ',total, ' Placement average: ', placement_avg)


College: 10  No.of Students:  111  Placement average:  56.75675675675676
College: 20  No.of Students:  247  Placement average:  58.2995951417004
College: 21  No.of Students:  340  Placement average:  59.705882352941174
College: 27  No.of Students:  214  Placement average:  66.35514018691589
College: 31  No.of Students:  588  Placement average:  74.31972789115646


In [ ]:
#5th week 11/9/24

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
for i in range(0, 32*7):
  fname = floc + str(i+1) + '.csv'
  data = np.genfromtxt(fname, delimiter=',')
  print(i+1, np.shape(data))

1 (125, 21)
2 (178, 21)
3 (293, 21)
4 (351, 21)
5 (745, 21)
6 (234, 21)
7 (608, 21)
8 (872, 21)
9 (965, 21)
10 (111, 21)
11 (352, 21)
12 (272, 21)
13 (306, 21)
14 (312, 21)
15 (367, 21)
16 (135, 21)
17 (109, 21)
18 (205, 21)
19 (195, 21)
20 (247, 21)
21 (340, 21)
22 (660, 21)
23 (176, 21)
24 (222, 21)
25 (256, 21)
26 (858, 21)
27 (214, 21)
28 (229, 21)
29 (440, 21)
30 (453, 21)
31 (588, 21)
32 (162, 21)
33 (125, 9)
34 (178, 4)
35 (293, 14)
36 (351, 15)
37 (745, 17)
38 (234, 12)
39 (608, 11)
40 (872, 17)
41 (965, 18)
42 (111, 12)
43 (352, 15)
44 (272, 17)
45 (306, 16)
46 (312, 18)
47 (367, 15)
48 (135, 14)
49 (109, 12)
50 (205, 8)
51 (195, 15)
52 (247, 11)
53 (340, 17)
54 (660, 15)
55 (176, 10)
56 (222, 15)
57 (256, 16)
58 (858, 16)
59 (214, 12)
60 (229, 13)
61 (440, 2)
62 (453, 16)
63 (588, 19)
64 (162, 8)
65 (125, 13)
66 (178, 3)
67 (293, 14)
68 (351, 15)
69 (745, 17)
70 (234, 11)
71 (608, 10)
72 (872, 17)
73 (965, 17)
74 (111, 10)
75 (352, 14)
76 (272, 19)
77 (306, 16)
78 (312, 15)
7

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import ranksums
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from matplotlib import pyplot

def normalizedata(X_train):
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    return X_train

In [ ]:
from sklearn.model_selection import KFold #fpr cross-validation


In [ ]:
np.random.shuffle(data) #shuffling data rowise

In [ ]:
kf = KFold(5)
for(tr_index, ts_index) in kf.split(data):
  print(tr_index, ts_index)

[ 72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 31

In [ ]:
model = []
model.append(MultinomialNB())
model.append(BernoulliNB())
model.append(GaussianNB())
model.append(LogisticRegression())
model.append(DecisionTreeClassifier())
model.append(svm.SVC(kernel = "linear"))
model.append(svm.SVC(kernel = "poly"))
model.append(svm.SVC(kernel = "rbf")) #Radial Basis Function

In [ ]:
model[7]

SVC()

In [ ]:
acc = np.zeros((32*7, 8))
for i in range(0, 32*7):
  fname = floc + str(i+1) + '.csv'
  data = np.genfromtxt(fname, delimiter=',')
  # print("College: "+ str(i+1))
  np.random.shuffle(data)
  data[:,0:-1] = normalizedata(data[:,0:-1])
  predictor = np.zeros((np.shape(data)[0],9))
  for(tr_index, ts_index) in kf.split(data):
      # print(tr_index, ts_index)
      tr_data = data[tr_index, 0:-1] #status
      tr_lab = data[tr_index, -1] #statistics
      # print(tr_lab)
      ts_data = data[ts_index, 0:-1]
      ts_lab = data[ts_index, -1]
      for j in range(0, 8):
          mod = model[j]
          mod.fit(tr_data, tr_lab)
          predictor[ts_index, j] = mod.predict(ts_data)
      predictor[ts_index, -1] = ts_lab

  for j in range(0, 8):
    acc[i, j] = (accuracy_score(predictor[:,-1], predictor[:,j])*100)


In [ ]:
np.shape(acc)

(224, 8)

In [ ]:
#assigned work

In [ ]:
#print accuracy for each college
for i in range(0, 32*7):
  print('College: '+ str(i+1), acc[i,:])

College: 1 [83.2 79.2 80.  82.4 74.4 82.4 81.6 84. ]
College: 2 [76.96629213 76.96629213 47.75280899 76.96629213 73.59550562 77.52808989
 76.96629213 77.52808989]
College: 3 [88.73720137 83.61774744 73.03754266 88.05460751 86.34812287 88.73720137
 88.73720137 89.07849829]
College: 4 [75.78347578 71.79487179 78.06267806 76.63817664 76.06837607 75.78347578
 77.20797721 77.20797721]
College: 5 [80.67114094 75.97315436 80.26845638 81.61073826 78.79194631 82.14765101
 81.0738255  81.34228188]
College: 6 [86.75213675 83.33333333 44.87179487 88.46153846 82.47863248 87.60683761
 86.75213675 87.17948718]
College: 7 [65.625      56.90789474 64.47368421 66.77631579 61.34868421 65.625
 69.24342105 66.94078947]
College: 8 [83.37155963 76.49082569 79.24311927 83.60091743 75.68807339 83.37155963
 83.94495413 83.37155963]
College: 9 [80.93264249 79.06735751 79.89637306 81.13989637 72.84974093 80.31088083
 80.7253886  80.41450777]
College: 10 [62.16216216 58.55855856 61.26126126 67.56756757 62.16216216

In [ ]:
np.savetxt(floc+'accuracy.csv', acc, delimiter=',', fmt='%f')

In [ ]:
acc1 = np.genfromtxt(floc+'accuracy.csv', delimiter=',')

acc1_df = pd.DataFrame(acc1)
models = ['MultinomialNB', 'BernoulliNB', 'GaussianNB', 'LogisticRegression', 'DecisionTreeClassifier', 'svc_linear', 'svc_poly', 'svc_rbf']
teest_ranges = ['original', 'z-test', 'rst', 'ccra', 'ccra_rst', 'gini', 'info_gain']
acc1_df.columns = models
acc1_df


MultinomialNB  BernoulliNB  GaussianNB  LogisticRegression  \
0        83.200000    79.200000   80.000000           82.400000   
1        76.966292    76.966292   47.752809           76.966292   
2        88.737201    83.617747   73.037543           88.054608   
3        75.783476    71.794872   78.062678           76.638177   
4        80.671141    75.973154   80.268456           81.610738   
..             ...          ...         ...                 ...   
219      67.248908    66.812227   56.331878           67.248908   
220      83.863636    82.500000   81.363636           83.863636   
221      84.768212    83.443709   86.754967           85.209713   
222      74.319728    72.959184   62.925170           74.319728   
223      51.234568    58.641975   57.407407           56.790123   

     DecisionTreeClassifier  svc_linear   svc_poly    svc_rbf  
0                 74.400000   82.400000  81.600000  84.000000  
1                 73.595506   77.528090  76.966292  77.528090  
2                 86.348123   88.737201  88.737201  89.078498  
3                 76.068376   75.783476  77.207977  77.207977  
4                 78.791946   82.147651  81.073826  81.342282  
..                      ...         ...        ...        ...  
219               65.938865   66.375546  65.938865  66.375546  
220               83.181818   83.863636  83.863636  84.090909  
221               83.222958   84.768212  88.079470  87.858720  
222               71.768707   74.319728  74.319728  74.319728  
223               64.197531   51.851852  66.049383  64.197531  

[224 rows x 8 columns]

In [ ]:
row_ranges = []
for test in teest_ranges:
    row_ranges += [f'{test}_{i}' for i in range(1, 33)]
acc1_df.index = row_ranges
acc1_df

MultinomialNB  BernoulliNB  GaussianNB  LogisticRegression  \
original_1        83.200000    79.200000   80.000000           82.400000   
original_2        76.966292    76.966292   47.752809           76.966292   
original_3        88.737201    83.617747   73.037543           88.054608   
original_4        75.783476    71.794872   78.062678           76.638177   
original_5        80.671141    75.973154   80.268456           81.610738   
...                     ...          ...         ...                 ...   
info_gain_28      67.248908    66.812227   56.331878           67.248908   
info_gain_29      83.863636    82.500000   81.363636           83.863636   
info_gain_30      84.768212    83.443709   86.754967           85.209713   
info_gain_31      74.319728    72.959184   62.925170           74.319728   
info_gain_32      51.234568    58.641975   57.407407           56.790123   

              DecisionTreeClassifier  svc_linear   svc_poly    svc_rbf  
original_1                 74.400000   82.400000  81.600000  84.000000  
original_2                 73.595506   77.528090  76.966292  77.528090  
original_3                 86.348123   88.737201  88.737201  89.078498  
original_4                 76.068376   75.783476  77.207977  77.207977  
original_5                 78.791946   82.147651  81.073826  81.342282  
...                              ...         ...        ...        ...  
info_gain_28               65.938865   66.375546  65.938865  66.375546  
info_gain_29               83.181818   83.863636  83.863636  84.090909  
info_gain_30               83.222958   84.768212  88.079470  87.858720  
info_gain_31               71.768707   74.319728  74.319728  74.319728  
info_gain_32               64.197531   51.851852  66.049383  64.197531  

[224 rows x 8 columns]

In [ ]:
acc1_df.to_csv(floc+'accuracy_file.csv')

In [ ]:
from matplotlib import pyplot as plt
def boxplot_all(data,test):
  plt.figure(figsize=(20,20))
  plt.boxplot(data,labels=models)
  plt.grid(True)
  plt.title(test)
  plt.xlabel('model_')
  plt.ylabel('accuracy_of')
  # plt.show()

  fname = floc + f"{test}" + '.png'
  plt.savefig(fname)
  plt.close()

In [ ]:
boxplot_all(acc1[:32],'College')

In [ ]:
for i in range(0, 7):
  boxplot_all(acc1[i*32:(i+1)*32],teest_ranges[i])

In [ ]:
data = pd.read_csv(floc + 'accuracy.csv', header=None)
ranks_list = []

for j in range(data.shape[0]):
    row_data = data.iloc[j, :]
    sorted_indices = np.argsort(row_data)[::-1]
    ranks = np.empty_like(sorted_indices)
    ranks[sorted_indices] = np.arange(1, 9)

    rank_row = pd.Series(ranks, index=models)
    ranks_list.append(rank_row)
ranks_df = pd.DataFrame(ranks_list, columns=models)

row_labels = []

for test in teest_ranges:
    row_labels += [f'{test}_{i}' for i in range(1, 33)]
ranks_df.index = row_labels
# print(ranks_df)
ranks_df.to_csv(floc + 'model_ranks.csv')


In [ ]:
acc2 = pd.read_csv(floc+'accuracy.csv')
# acc2
acc2.shape

(223, 8)

In [ ]:
acc2['Average_College_Test'] = acc2.mean(axis=1)
acc2

83.200000  79.200000  80.000000  82.400000  74.400000  82.400000.1  \
0    76.966292  76.966292  47.752809  76.966292  73.595506    77.528090   
1    88.737201  83.617747  73.037543  88.054608  86.348123    88.737201   
2    75.783476  71.794872  78.062678  76.638177  76.068376    75.783476   
3    80.671141  75.973154  80.268456  81.610738  78.791946    82.147651   
4    86.752137  83.333333  44.871795  88.461538  82.478632    87.606838   
..         ...        ...        ...        ...        ...          ...   
218  67.248908  66.812227  56.331878  67.248908  65.938865    66.375546   
219  83.863636  82.500000  81.363636  83.863636  83.181818    83.863636   
220  84.768212  83.443709  86.754967  85.209713  83.222958    84.768212   
221  74.319728  72.959184  62.925170  74.319728  71.768707    74.319728   
222  51.234568  58.641975  57.407407  56.790123  64.197531    51.851852   

     81.600000  84.000000  Average_College_Test  
0    76.966292  77.528090             73.033708  
1    88.737201  89.078498             85.793515  
2    77.207977  77.207977             76.068376  
3    81.073826  81.342282             80.234899  
4    86.752137  87.179487             80.929487  
..         ...        ...                   ...  
218  65.938865  66.375546             65.283843  
219  83.863636  84.090909             83.323863  
220  88.079470  87.858720             85.513245  
221  74.319728  74.319728             72.406463  
222  66.049383  64.197531             58.796296  

[223 rows x 9 columns]

In [ ]:
model_avg = acc2.mean(axis=0)
acc2.loc['model_avg'] = model_avg
acc2

83.200000  79.200000  80.000000  82.400000  74.400000  82.400000.1  \
0          76.966292  76.966292  47.752809  76.966292  73.595506    77.528090   
1          88.737201  83.617747  73.037543  88.054608  86.348123    88.737201   
2          75.783476  71.794872  78.062678  76.638177  76.068376    75.783476   
3          80.671141  75.973154  80.268456  81.610738  78.791946    82.147651   
4          86.752137  83.333333  44.871795  88.461538  82.478632    87.606838   
...              ...        ...        ...        ...        ...          ...   
219        83.863636  82.500000  81.363636  83.863636  83.181818    83.863636   
220        84.768212  83.443709  86.754967  85.209713  83.222958    84.768212   
221        74.319728  72.959184  62.925170  74.319728  71.768707    74.319728   
222        51.234568  58.641975  57.407407  56.790123  64.197531    51.851852   
model_avg  76.581228  75.231935  71.255447  78.228060  74.926609    77.822355   

           81.600000  84.000000  Average_College_Test  
0          76.966292  77.528090             73.033708  
1          88.737201  89.078498             85.793515  
2          77.207977  77.207977             76.068376  
3          81.073826  81.342282             80.234899  
4          86.752137  87.179487             80.929487  
...              ...        ...                   ...  
219        83.863636  84.090909             83.323863  
220        88.079470  87.858720             85.513245  
221        74.319728  74.319728             72.406463  
222        66.049383  64.197531             58.796296  
model_avg  78.247279  78.566126             76.357380  

[224 rows x 9 columns]

In [ ]:
# acc2.to_csv(floc+'accuracy_with_avg.csv')

In [ ]:
# 6th week  18-9-24

In [ ]:
np.random.randint(0,5,[5,2]) #generating 5x2 random array between 0-4

array([[4, 1],
       [2, 1],
       [3, 3],
       [2, 2],
       [4, 0]])

In [ ]:
model = DecisionTreeClassifier()
def accuracy_value(data):
  np.random.shuffle(data)
  data[:,0:-1] = normalizedata(data[:,0:-1])
  predictor = np.zeros((np.shape(data)[0], 2))
  for tr_index, ts_index in kf.split(data):
      # print(tr_index, ts_index)
      tr_data = data[tr_index, 0:-1] #status
      tr_lab = data[tr_index, -1] #statistics
      # print(tr_lab)
      ts_data = data[ts_index, 0:-1]
      ts_lab = data[ts_index, -1]
      model.fit(tr_data, tr_lab)
      predictor = model.predict(ts_data)
  return accuracy_score(predictor, ts_lab)

In [ ]:
data = np.genfromtxt(floc+'demodata.csv', delimiter=',')
accuracy_value(data)

0.9154929577464789

fitness value high-acc parallely low-no.of.features
0.8*acc + (20 - no.of-features_suggested)/20 * 0.2

In [ ]:
nof = np.shape(data)[1]-1
chr = np.random.randint(0,2,[50, nof]) #50 chromosomes i.e 50 solutions
chr

array([[0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 1,

In [ ]:
np.shape(chr)

(50, 20)

In [ ]:
in1 = np.where(chr[0,:] == 1)
in1[0]

array([ 0,  4,  5,  6,  8, 11, 15, 18, 19])

In [ ]:
from copy import copy

def fitness(chr, data):
  fit = np.zeros((np.shape(chr)[0], 3))
  for i in range(0, np.shape(chr)[0]):
    c = chr[i, :]
    in1 = np.where(c==1)
    data1 = copy(data)
    data1 = data1[:, in1[0]]
    data1 = np.concatenate((data1, data[:,-1].reshape(-1,1)), axis=1)
    acc = accuracy_value(data1)
    fit[i, 0] = acc
    fit[i, 1] = len(in1[0])
    fit[i, 2] = 0.8*acc + (20-len(in1[0]))/20 * 0.2
  return fit

In [ ]:
fit = fitness(chr, data) #acc ---- no.of.features_suggested ---- overall_fitness_value
fit

array([[ 0.68571429, 10.        ,  0.64857143],
       [ 0.57142857, 12.        ,  0.53714286],
       [ 0.74285714,  8.        ,  0.71428571],
       [ 0.71428571,  6.        ,  0.71142857],
       [ 0.68571429, 14.        ,  0.60857143],
       [ 0.8       , 10.        ,  0.74      ],
       [ 0.65714286,  9.        ,  0.63571429],
       [ 0.74285714, 11.        ,  0.68428571],
       [ 0.77142857, 14.        ,  0.67714286],
       [ 0.62857143,  8.        ,  0.62285714],
       [ 0.8       ,  9.        ,  0.75      ],
       [ 0.51428571, 12.        ,  0.49142857],
       [ 0.74285714, 11.        ,  0.68428571],
       [ 0.74285714,  9.        ,  0.70428571],
       [ 0.65714286,  7.        ,  0.65571429],
       [ 0.71428571, 13.        ,  0.64142857],
       [ 0.74285714,  9.        ,  0.70428571],
       [ 0.71428571,  9.        ,  0.68142857],
       [ 0.65714286, 16.        ,  0.56571429],
       [ 0.8       , 10.        ,  0.74      ],
       [ 0.6       , 12.        ,  0.56 

In [ ]:
#to get which fitnes is best ()
a = np.argmax(fit[:, 2])
fit[a, :]

array([0.95774648, 5.        , 0.91619718])

In [ ]:
#CROSS_OVER to increase the overall performance of the model
# by forming random groups of 2

In [ ]:
def crossover(chr):
  no_of_chr = np.shape(chr)[0]
  np.random.shuffle(chr)
  new_chr = np.zeros((int(no_of_chr/2), np.shape(chr)[1]))
  for i in range(0, int(no_of_chr/2)):
    new_chr[i,0:10] = chr[2*i, 0:10] #taking the first 10 features of the 2ith chr
    new_chr[i,10:] = chr[2*i+1, 10:] #next 10 features of the 2i+1 th chr  -- this creates a new chromosome based on two parents
  return new_chr

In [ ]:
co = crossover(chr)
# co
np.shape(co)

(25, 20)

In [ ]:
#mutation -- minor chages to increase performance further more

In [ ]:
def mutation(chr):
  change = np.random.randint(0, np.shape(chr)[1], [np.shape(chr)[0], 2])
  for i in range(0, np.shape(chr)[0]):
    chr[i, change[i, 0]] = 1-chr[i, change[i, 0]] #making all zeros to ones and ones to zeros
    chr[i, change[i, 1]] = 1-chr[i, change[i, 1]]
  return chr

In [ ]:
chr = mutation(chr)
chr

array([[1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 0,

In [ ]:
#genetic algo
def GA(data):
  chr = np.random.randint(0,2,[50, np.shape(data)[1]-1])
  # print('accuracy with all features = ' + str(accuracy_value(data)))
  best_fit = 0 #best fitness value
  gen = 0 #iteration or generation
  while(gen <= 20):
    fit = fitness(chr, data)
    a = np.argmax(fit[:, 2])

    current_best_fit = fit[a, 2]
    if current_best_fit > best_fit:
      best_fit = current_best_fit
      best_accuracy = fit[a, 0]
      best_nof_features = fit[a, 1]
      best_chr = copy(chr[a, :])

    chr[0:25, :] = crossover(chr) #replacing our original 50 chromosomes to 25 with crossover
    chr[0:25, :] = mutation(chr[0:25, :]) #appliies mutation on above generated cross-over chrs and replace them from 0-25 again
    chr[25:, :] =  np.random.randint(0,2,[25, np.shape(chr)[1]])   #regeneration

    in1 = np.where(best_chr==1)
    best_fts = data[:, in1[0]]

    gen = gen + 1
    # print('best acc = ',best_accuracy,'bnof = ',best_nof_features, "best_chrs", best_chr)
  return best_fts


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
floc = '/content/drive/MyDrive/DataMining/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
fname = floc+ '2.csv'
data = np.genfromtxt(fname, delimiter=',')
ga = GA(data)
print(ga)

[[ 14.        0.       33.      ...   0.35714   1.        1.5714 ]
 [  5.        0.        0.      ...   0.53333   3.        0.8    ]
 [ 13.        1.       46.      ...   0.61538   0.        0.7692 ]
 ...
 [ 23.        0.      201.      ...   0.31818   0.        2.3043 ]
 [ 11.        8.       15.      ...   0.26667   0.        4.6364 ]
 [  4.        0.        0.      ...   0.875     1.        1.75   ]]


In [ ]:
for i in range(0, 32):
  fname = floc + str(i+1) + '.csv'
  data = np.genfromtxt(fname, delimiter=',')
  ga = GA(data)
  print(str(i+1), "th college")
  np.savetxt(floc+str((32*7)+i+1)+'.csv', ga, delimiter=',', fmt='%f')

1 th college
2 th college
3 th college
4 th college
5 th college
6 th college
7 th college
8 th college
9 th college
10 th college
11 th college
12 th college
13 th college
14 th college
15 th college
16 th college
17 th college
18 th college
19 th college
20 th college
21 th college
22 th college
23 th college
24 th college
25 th college
26 th college
27 th college
28 th college
29 th college
30 th college
31 th college
32 th college


In [ ]:
ga = GA(data)
ga

accuracy with all features = 0.7142857142857143
best acc =  0.8285714285714286 bnof =  8.0 best_chrs [1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0]
best acc =  0.8285714285714286 bnof =  8.0 best_chrs [1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0]
best acc =  0.8285714285714286 bnof =  8.0 best_chrs [1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0]
best acc =  0.8285714285714286 bnof =  8.0 best_chrs [1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0]
best acc =  0.8571428571428571 bnof =  5.0 best_chrs [0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0]
best acc =  0.8857142857142857 bnof =  7.0 best_chrs [1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0]
best acc =  0.8857142857142857 bnof =  7.0 best_chrs [1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0]
best acc =  0.8857142857142857 bnof =  7.0 best_chrs [1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0]
best acc =  0.9142857142857143 bnof =  9.0 best_chrs [1 1 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 1 0]
best acc =  0.9142857142857143 bnof =  9.0 best_chrs [1 1 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 1 0]
be

(0.8857142857142857,
 6.0,
 array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]))

In [ ]:
np.shape(chr[1])

(20,)

asssigned work

apply ga on all 32 data and save as continuation (8th set).

approach to say that if anyone is using any feature selection technique (ccra, rst, z-test, info-gain, gini, ga, ccra_rst) for cllg 32 what are the features important.

to display in a framework for cllg 30 if we use ga then what are the important features in Graph.

next lab-- text mining



In [ ]:
for i in range(0, 32):
  fname = floc + str(i+1) + '.csv'
  data = np.genfromtxt(fname, delimiter=',')
  ga = GA(data)
  print(ga)

In [ ]:
imp_features_8T = np.zeros((32, 8))
for i in range(0, 32):
  for j in range(0, 8):
    fname = floc + str((i+1)+ 32*j) + '.csv'
    data = np.genfromtxt(fname, delimiter=',')
    imp_features_8T[i, j] = np.shape(data)[1]-1

print(imp_features_8T)
np.savetxt(floc + "imp_fts_8T.csv", imp_features_8T, delimiter=',', fmt='%f')

[[20.  8. 12. 10.  6.  5.  5.  8.]
 [20.  3.  2. 10.  1.  5.  5.  6.]
 [20. 13. 13. 10.  7.  5.  5.  4.]
 [20. 14. 14. 10.  7.  5.  5.  4.]
 [20. 16. 16. 10.  8.  5.  5.  4.]
 [20. 11. 10. 10.  5.  5.  5.  3.]
 [20. 10.  9. 10.  5.  5.  5.  6.]
 [20. 16. 16. 10.  8.  5.  5.  4.]
 [20. 17. 16. 10.  8.  5.  5.  2.]
 [20. 11.  9. 10.  5.  5.  5.  4.]
 [20. 14. 13. 10.  7.  5.  5.  5.]
 [20. 16. 18. 10.  9.  5.  5.  9.]
 [20. 15. 15. 10.  8.  5.  5.  5.]
 [20. 17. 14. 10.  7.  5.  5.  7.]
 [20. 14. 14. 10.  7.  5.  5.  6.]
 [20. 13. 13. 10.  7.  5.  5.  6.]
 [20. 11. 12. 10.  6.  5.  5.  6.]
 [20.  7.  4. 10.  2.  5.  5.  2.]
 [20. 14. 12. 10.  6.  5.  5.  8.]
 [20. 10. 12. 10.  6.  5.  5.  4.]
 [20. 16. 17. 10.  9.  5.  5.  8.]
 [20. 14. 15. 10.  8.  5.  5.  4.]
 [20.  9.  8. 10.  4.  5.  5.  7.]
 [20. 14. 14. 10.  7.  5.  5.  8.]
 [20. 15. 15. 10.  8.  5.  5.  9.]
 [20. 15. 13. 10.  7.  5.  5.  6.]
 [20. 11. 14. 10.  7.  5.  5.  7.]
 [20. 12. 12. 10.  6.  5.  5.  5.]
 [20.  1.  2. 10.  1

In [ ]:
imp_fts = pd.read_csv(floc + 'imp_fts_8T.csv', header=None)
# imp_fts
teest_ranges = ['original', 'z-test', 'rst', 'ccra', 'ccra_rst', 'gini', 'info_gain', "GA"]
imp_fts.columns = teest_ranges
imp_fts

original  z-test   rst  ccra  ccra_rst  gini  info_gain   GA
0       20.0     8.0  12.0  10.0       6.0   5.0        5.0  8.0
1       20.0     3.0   2.0  10.0       1.0   5.0        5.0  6.0
2       20.0    13.0  13.0  10.0       7.0   5.0        5.0  4.0
3       20.0    14.0  14.0  10.0       7.0   5.0        5.0  4.0
4       20.0    16.0  16.0  10.0       8.0   5.0        5.0  4.0
5       20.0    11.0  10.0  10.0       5.0   5.0        5.0  3.0
6       20.0    10.0   9.0  10.0       5.0   5.0        5.0  6.0
7       20.0    16.0  16.0  10.0       8.0   5.0        5.0  4.0
8       20.0    17.0  16.0  10.0       8.0   5.0        5.0  2.0
9       20.0    11.0   9.0  10.0       5.0   5.0        5.0  4.0
10      20.0    14.0  13.0  10.0       7.0   5.0        5.0  5.0
11      20.0    16.0  18.0  10.0       9.0   5.0        5.0  9.0
12      20.0    15.0  15.0  10.0       8.0   5.0        5.0  5.0
13      20.0    17.0  14.0  10.0       7.0   5.0        5.0  7.0
14      20.0    14.0  14.0  10.0       7.0   5.0        5.0  6.0
15      20.0    13.0  13.0  10.0       7.0   5.0        5.0  6.0
16      20.0    11.0  12.0  10.0       6.0   5.0        5.0  6.0
17      20.0     7.0   4.0  10.0       2.0   5.0        5.0  2.0
18      20.0    14.0  12.0  10.0       6.0   5.0        5.0  8.0
19      20.0    10.0  12.0  10.0       6.0   5.0        5.0  4.0
20      20.0    16.0  17.0  10.0       9.0   5.0        5.0  8.0
21      20.0    14.0  15.0  10.0       8.0   5.0        5.0  4.0
22      20.0     9.0   8.0  10.0       4.0   5.0        5.0  7.0
23      20.0    14.0  14.0  10.0       7.0   5.0        5.0  8.0
24      20.0    15.0  15.0  10.0       8.0   5.0        5.0  9.0
25      20.0    15.0  13.0  10.0       7.0   5.0        5.0  6.0
26      20.0    11.0  14.0  10.0       7.0   5.0        5.0  7.0
27      20.0    12.0  12.0  10.0       6.0   5.0        5.0  5.0
28      20.0     1.0   2.0  10.0       1.0   5.0        5.0  4.0
29      20.0    15.0  15.0  10.0       8.0   5.0        5.0  2.0
30      20.0    18.0  16.0  10.0       8.0   5.0        5.0  8.0
31      20.0     7.0   6.0  10.0       3.0   5.0        5.0  6.0

In [ ]:
# 7th week 25/9/24